### ISSUE TITLE
parameter explaination?

### ISSUE THREAD

**Issue by Selur** [WolframRhodium/VapourSynth-WNNM#1]
Would be nice if the documentation could be expanded a bit to give some basic info about what the parameters are for and what are their min/max and valid values.

**Comment by WolframRhodium** [comment]
`sigma` controls the strength of denoising, and every other parameter is the same as in [VapourSynth-BM3D](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D)

`residual` and `adaptive_aggregation` are not considered stable and may be removed, especially the latter one.

**Comment by Selur** [comment]
Thanks 👍 :)
