### ISSUE TITLE
Question about range=0.

### ISSUE THREAD

**Issue by Selur** [WolframRhodium/VapourSynth-WNNM#2]
Output seems broken when the default range=0 is used, or is ist some sort of 'mask view' ?
range 0:
![wnnm_range_zero](https://user-images.githubusercontent.com/843640/171048287-e13e19b0-4676-46c3-a142-66d334df019a.png)
range 1:
![wnnm_range_one](https://user-images.githubusercontent.com/843640/171048299-52860875-588e-4d4b-b0ed-d1e8df6e0699.png)

**Comment by WolframRhodium** [comment]
It must be a bug. Which version of wnnm and parameters are you using?

**Comment by Selur** [comment]
I think I used:
https://github.com/WolframRhodium/VapourSynth-WNNM/actions/runs/2395422690
and simply called:
clip = core.wnnm.WNNM(clip=clip)
just tried:
https://github.com/WolframRhodium/VapourSynth-WNNM/actions/runs/2412968042
and there the issue is gone. :)
Thanks.
