### ISSUE TITLE
any chance we can get a way to not process certain planes in order to get a performance boost

### ISSUE THREAD

**Issue by BReza27** [WolframRhodium/VapourSynth-WNNM#3]
It would be nice if it could be used on only luma or only chroma in order to get a speedup if possible. at the moment when sigma for a certain plane is set to 0 it just errors saying something along the lines of: 
2022-05-30 23:29:31.844: CRITICAL: Error in frame creation: dimensions of plane 0 do not match. Source: 1920x1080; destination: 1920x15120
VapourSynth encountered a fatal error: Error in frame creation: dimensions of plane 0 do not match. Source: 1920x1080; destination: 1920x15120

**Comment by WolframRhodium** [comment]
Thanks!

**Comment by BReza27** [comment]
Awesome. Works properly now
